plugins {
  id 'java'
  //id 'com.github.johnrengelman.shadow' version '8.1.1'
	id 'fabric-loom' version '1.10-SNAPSHOT'
	id 'maven-publish'
}

archivesBaseName = project.archives_base_name
version = project.mod_version
group = project.maven_group

repositories {
	// Add repositories to retrieve artifacts from in here.
	// You should only use this when depending on other mods because
	// Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
	// See https://docs.gradle.org/current/userguide/declaring_repositories.html
	// for more information about repositories.
  maven {
    name = "CottonMC"
    url = "https://server.bbkr.space/artifactory/libs-release"
  }
	maven { url 'https://jitpack.io' }
}

dependencies {
	// To change the versions see the gradle.properties file
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

  // bundle the external mods
  modImplementation include("io.github.cottonmc:LibGui:${project.libgui_version}")
	modImplementation include("com.github.hashicraft:fabric-stateful-mod:${stateful_version}")

  // include the libraries  
  include implementation("org.postgresql:postgresql:42.6.0");
  include implementation("io.javalin:javalin:6.6.0");
  include implementation("io.javalin.community.ssl:ssl-plugin:6.6.0");
  include implementation("com.jayway.jsonpath:json-path:2.9.0");
  include implementation("io.github.kawamuray.wasmtime:wasmtime-java:${wasmtime_version}")

  // undertow webserver and jboss dependencies
  include implementation("io.undertow:undertow-core:2.3.18.Final")
  include implementation("org.jboss.threads:jboss-threads:3.5.0.Final")
  include implementation("org.jboss.logging:jboss-logging:3.4.3.Final")
  include implementation("org.jboss.xnio:xnio-api:3.8.16.Final")  

  testImplementation("com.jayway.jsonpath:json-path:2.9.0")
  testImplementation 'com.google.code.gson:gson:2.13.1'
  
  testImplementation "net.fabricmc:fabric-loader-junit:${project.loader_version}"
  testImplementation('uk.org.webcompere:system-stubs-jupiter:2.1.6')
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	// ensure that the encoding is set to UTF-8, no matter what the system default is
	// this fixes some edge cases with special characters not displaying correctly
	// see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
	// If Javadoc is generated, this must be specified in that task too.
	it.options.encoding = "UTF-8"

	// Minecraft 1.17 (21w19a) upwards uses Java 16.
	it.options.release = 21
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	from("LICENSE") {
		rename { "${it}_${project.archivesBaseName}"}
	}
}

// configure the maven publication
publishing {
	publications {
		mavenJava(MavenPublication) {
			// add all the jars that should be included when publishing to maven
			artifact(remapJar) {
				builtBy remapJar
			}
			artifact(sourcesJar) {
				builtBy remapSourcesJar
			}
		}
	}

	// See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
	repositories {
		// Add repositories to publish to here.
		// Notice: This block does NOT have the same function as the block in the top level.
		// The repositories here will be used for publishing your artifact, not for
		// retrieving dependencies.
	}
}

test {
	useJUnitPlatform()
}